import type { Category, Task } from '../domain/models';
interface Props { tasks: readonly Task[]; categories: readonly Category[]; onCreate(): void; onEdit(task: Task): void; onDelete(id: string): void; onStatus(id: string, status: Task['status']): void; }
export function TaskList({ tasks, categories, onCreate, onEdit, onDelete, onStatus }: Props) {
  const categoryName = (id: string): string => categories.find((category) => category.id === id)?.name ?? 'Unknown';
  const sections: Array<{ title: string; className: string; tasks: Task[] }> = [
    { title: 'Active tasks', className: 'active', tasks: tasks.filter((task) => task.status === 'todo' || task.status === 'in-progress') },
    { title: 'Completed tasks', className: 'completed', tasks: tasks.filter((task) => task.status === 'done') },
    { title: 'Archived tasks', className: 'archived', tasks: tasks.filter((task) => task.status === 'archived') },
  ];
  return <section className="task-list" aria-label="Task list">{sections.filter((section) => section.className === 'active' || section.tasks.length > 0).map((section) => <section className={`task-section ${section.className}`} key={section.className} aria-label={section.title}><div className="section-heading"><h2>{section.title}</h2>{section.className === 'active' && <button className="create-task" onClick={onCreate}>Create task</button>}</div>{section.tasks.length === 0 ? <p className="empty">No tasks match the current view.</p> : section.tasks.map((task) => <article className={`task ${task.status}`} key={task.id}><div><div className="task-heading">{task.status === 'done' && <span className="completion-mark" aria-label="Completed">✓</span>}<h3>{task.title}</h3><span className={`priority ${task.priority}`}>{task.priority}</span></div><p>{task.description}</p><small>{categoryName(task.categoryId)} {task.dueDate ? `| Due ${task.dueDate}` : ''}</small></div><div className="task-actions"><select aria-label={`Status for ${task.title}`} value={task.status} onChange={(event) => onStatus(task.id, event.target.value as Task['status'])}><option value="todo">To do</option><option value="in-progress">In progress</option><option value="done">Done</option><option value="archived">Archived</option></select><button onClick={() => onEdit(task)}>Edit</button><button className="danger" onClick={() => onDelete(task.id)}>Delete</button></div></article>)}</section>)}</section>;
}